### ISSUE TITLE
Kindly take down this repository before you get yourself and your family in legal trouble.

### ISSUE THREAD

**Issue by Benedani** [stalechilibeans/b3313#1]
Title. You (the owner of this repository) are publically hosting copyright protected material from Nintendo (multiple copies of Super Mario 64) as well as the B3313 development team (the source code and the binaries), neither of which you have any rights to.

Copyrighted material is not something you just fuck around with. Since I presume you are below the age of being legally held accountable for, that burden will be transferred to your parents / legal guardians. I can't imagine a world where getting into legal trouble over maro 64 betes from not one, but two parties (us, as well as Nintendo's legal team) would be a great situation for your family relationships.

You have 24 hours to take down the repository and erase all traces of the source code across all of your storage mediums, and reconsider your life decisions, before I consult [GitHub's DMCA system](https://docs.github.com/en/site-policy/content-removal-policies/guide-to-submitting-a-dmca-takedown-notice) as well as [Nintendo's legal team](https://en-americas-support.nintendo.com/app/answers/detail/a_id/50131/~/how-to-report-potential-infringements-of-nintendo-products), which I very well could have already done immediately.

**Comment by Benedani** [comment]
@stalechilibeans ^ in case you didn't get a notification.

**Comment by stalechilibeans** [comment]
@Benedani who do you think you are to threaten to legally get my in trouble over a silly sm64 rom hack? well, you're certainly a moron
![image](https://github.com/stalechilibeans/b3313/assets/73906828/c444f0b8-9ebd-4ee9-988e-8c82bf3c5d8f)

b3313 isn't copyrighted and you're an sm64 hacker as well, benedani. also, 'publically' isn't a damn word, learn the language please.

i'll get this repository taken down (once i get a reply from you, that is) but only because you and your lovers (*cough, cough* josh...) want it to be gone. you're welcome in advance.

**Comment by stalechilibeans** [comment]
friendly reminder that you're very likely to go down along with me if you consult nintendo's legal team over this, and for OBVIOUS reasons (hell, not just you... b3313's entire development team, perhaps even including chris' side of it)

**Comment by spongetoo** [comment]
>Nintendo's legal team
are you sure, you're gonna let nintendo to take most b3313-related stuff down, to the point where it spreads to sm64 beta projects like The Preservation Project? huh?

@Benedani think wisely pls before doing anything hihi ^-^

**Comment by Benedani** [comment]
> @Benedani who do you think you are to threaten to legally get my family in trouble over a silly sm64 rom hack? well, you're certainly a moron

This is not the first DMCA takedown notice I've submitted related to my content, and as I see it, it certainly won't be the last, either. You have no rights to host or distribute the Troll Engine. Doing so is a direct violation of copyright law.
Should there be any legal case as a result of your behavior (it would be pretty funny if you filed a counter notice), assuming you are underage, your family will have to be the ones to represent you in court. That is simply how legal cases work. I don't make the rules.

> also, 'publically' isn't a damn word, learn the language please.

Thank you for the correction. Unfortunately, this is a classic case of [ad hominem](https://en.wikipedia.org/wiki/Ad_hominem).

**Comment by Benedani** [comment]
> and if you ignore me the downfall of beta hacks will happen :trollface:

Try telling me with a straight face that that would not be a good thing.
